### ISSUE TITLE
会場の場所

### ISSUE THREAD

**Issue by acevif** [wantedly/ios_night#24]
会場の場所とかREADME.md にあると分かりやすいかもと思いました

**Comment by ngtk** [comment]
こんにちは。初めまして、Wantedlyの永田と申します！
確かに場所が書いてあると良いですね。そうします！

**Comment by acevif** [comment]
ありがとうございます！🙏

**Comment by MizuTakeuchi** [comment]
@acevif 
12月も開催するので、よかったらぜひきてください！
12月は、4,11,18,25日に開催します。
ご都合いかがでしょう？？

**Comment by acevif** [comment]
@MizuTakeuchi お知らせくださってありがとうございます！
では12/4に伺います!

**Comment by MizuTakeuchi** [comment]
ありがとうございます！
19:00から開始しますので、少し前にオフィスに到着いただけると嬉しいです。

〒108-0071 東京都港区白金台5-12-7 MG白金台ビル
最寄り駅：白金台徒歩8分、目黒駅14分
受付に到着しましたら4階受付にて竹内瑞季または永田をお呼び出しください。
