### ISSUE TITLE
Operation Improvement 2019/05/20

### ISSUE THREAD

**Issue by ngtk** [wantedly/ios_night#51]
## Why
[前回](https://github.com/wantedly/ios_night/issues/49#issuecomment-492182509) 振り返りをみんなで取り組み、意見は出たので取り組む改善案を決めて改善していきたい。

> ## Keep
> - 継続できている！
> - 学びが多い
> - チーム間でのコミュニケーションが増えた
> - みんながネタを書くようになった
> - 外部の人も参加するようになった
> - 1時間でサクッと終わるのが良い
> 
> 
> ## Problem / Try
> - 学生の参加者がいる場合についてこれないケースがある
>   - もうちょっと軽いネタを入れる
> - 社内でサーブされる夕食の時間と開始時間が同じなので参加者だけ食べない現象が起きる
>  - 19時から食べる、19時30分開始にする
> - ラウンジでやっていた時があるが、周りがうるさくて聞こえないことがあった
>   - Pearl Jamでやるので固定する
> - コードも書きたい
>   - コードを書く日を作る (テーマを決める・モブプロ？) @ngtk が考える
> - 外部ゲスト対応は少し心理的ハードルがある
>   -  外部ゲストが来る日を月初だけにする
> - 外部ゲスト対応が少し塩
>   - 終わった後に懇親タイムを作る

## What
改善することをリストして、完了させる。

## Ref
運用についてのまとめ: https://github.com/wantedly/ios_night/issues/52

**Comment by ngtk** [comment]
## 取り組むこと

- [ ] 「iOSに関連する話題ならなんでも良いこと」「タイトルだけの提供でもOK」という点をIssue templateに追記
- [x] 19時から食べる、19時30分開始にするため、カレンダーの時間を変える
- [x] 会議室はPearl Jamで固定
- [x] 毎月3週目をモブプロの日にし、第2週目にお題を決める
- [x] 初参加の外部ゲストは基本的に毎月第1週に受け入れにする
- [x] 自己紹介フォーマットを作る
- [x] 「 1人1ネタ持参は必須 (全員喋る)」をREADME/Issue Templateに追記
- [ ] Twitter当番を決めて運用する (wantedly-devを使う)
- [x] ファシリテーションを @ShotaKashihara さんと交互にしたい => OKもらった https://github.com/wantedly/ios_night/issues/51#issuecomment-493924034
- [x] 前回のIssueを貼れるようにIssue Tempateを変更する

**Comment by ngtk** [comment]
@ShotaKashihara 
> ファシリテーションを @ShotaKashihara さんと交互にしたい

次次回(5/28)からお願いしても良いですか？
やることは、準備(Issue作成, メンバーへのリマインド)と司会進行です。

**Comment by ngtk** [comment]
> 初参加の外部ゲストは基本的に毎月第1週に受け入れにする

この件に関しては @MizuTakeuchi さんにも相談してこの方針で行くことに決めた。
Wantedlyでミートアップ募集も出しているので、運用も変更してもらった。

cc: @wantedly/ios

**Comment by ngtk** [comment]
>  19時から食べる、19時30分開始にするため、カレンダーの時間を変える

これに関しては次回(明日5/21)はすでに外部参加者がいるため、次次回(5/28)からとする。
カレンダーには反映済み。README/Issue Templateにも反映済み。

**Comment by ngtk** [comment]
> 次次回(5/28)からお願いしても良いですか？
> やることは、準備(Issue作成, メンバーへのリマインド)と司会進行です。

口頭でOKをもらった。
5/28は予定があるようなので、明日5/20でお願いした。
また、お互いに参加が難しい場合は適宜選手交代する。

**Comment by ShotaKashihara** [comment]
おっけー！
