### ISSUE TITLE
2019/11/19 19:30~20:30

### ISSUE THREAD

**Issue by jiro** [wantedly/ios_night#75]
⚠️ This repository is public. / 公開リポジトリです。

## Why
- For Enhancing our skills 💪
- For enjoying iOS/Swift development 🥳

## Where
Pearl Jam (Subject to change)

5F, MG Shirokanedai Building (Wantedly, Inc. Tokyo HQ)

## Who
You are working for Wantedly? Sure, you can join anytime.
If not, you need to contact us first. Or, you can "want to visit" the meetup, which you can find in www.wantedly.com/companies/wantedly/projects.

## What
You write topics like below contents and we talk about these on the meetup. Every participant needs to write one topic at least.

- News topics you found ✨
- Questions or issues you have on your daily development 🤔
- Today's Shortcuts ⛳️

Also, you can find new topics from the newsletters:

- https://iosdevweekly.com/issues
- http://ios-goodies.com/
- https://www.swiftbysundell.com/
- https://forums.swift.org/top/weekly
- https://swiftweekly.github.io/
- https://nshipster.com/
- https://www.pointfree.co/blog

## How

- Don't hassle to prepare
- Everyone can join and leave in the middle
- Do not skip if we have few attendees

　　　　　　　　　・・・

参加者は開催までに話したいことを少なくとも1トピックをコメントしましょう。
ネタ被りを避けるために、まずはタイトルだけでコメントすることを推奨します。
より多くの学びを得るためにどんな内容でもアウトプットを歓迎します！😊

cc/ @wantedly/ios

[Edit this template](https://github.com/wantedly/ios_night/edit/master/.github/ISSUE_TEMPLATE/start-next-meeting.md)

**Comment by jiro** [comment]
## Introducing the Apple Developer App

https://developer.apple.com/news/?id=11182019a

WWDCアプリがApple Developerアプリとしてリニューアル

> Starting today, the WWDC app is now the Apple Developer app and delivers in-depth information from Apple experts all year round. Stay up to date with the latest developer news, informative videos, WWDC content, and more.

**Comment by ngtk** [comment]
## Secret Management on iOS
https://nshipster.com/secrets/

> 🧠 NORMAL BRAIN
> Hard-Code Secrets in Source Code

_普通の人たち_

ソースコードにハードコードするのはよくない。
リバースエンジニアリングをすればすぐに解読できる。

> 🧠 BIG BRAIN
> Store Secrets in Xcode Configuration and Info.plist

_考える人たち_

12-Factor Appにあるように設定値や環境変数はコードとは別にした方が良い。
Info.plistに特秘値を書いていく。そうすると当然コードのリバースエンジニアリングはできないが、ファイルとしてむしろ簡単にアクセスできるようになってしまう。

> 🧠 COSMIC BRAIN
> Obfuscate Secrets Using Code Generation

_すごい人たち_

特秘値はコミットせずに、特秘値を難読化したコードを自動生成するコードを書く。
そうするとコード自体はリバースエンジニアリングされても、簡単に読むことはできなくなる。

> 🧠 GALAXY BRAIN
> Don’t Store Secrets On-Device

_めちゃすごい人たち_

Secure Enclaveを利用して、特秘値を安全に取得して格納することができる。
Appleの以下の仕組みを利用することもできる:

> - On-Demand Resources: Download a data asset containing a plain-text secret.
> - CloudKit Database: Set secrets in a private database in your CloudKit Dashboard. (Bonus: Subscribe to changes for automatic credential rolling functionality)
> - Background Updates: Push secrets silently to clients as soon as they come online via APNS.

Secure Enclaveは安全だが、利用用途が意図しないかもしれない。

> 🧠 UNIVERSE BRAIN
> Client Secrecy is Impossible

_悟った人たち_

そもそもクラインアントで実行される限り、クラインアントで安全に保持することは難しい。
例えばAPIのキーであれば、サーバーで処理できないかを考えるべき。

彼らの結論は以下:

> Restating our original question: “How do I store secrets securely on the client?”
> 
> Our answer: “Don’t (but if you must, obfuscation wouldn’t hurt).”

**最初に質問に立ち戻ると: 「クラインとでどのようにシークレットを安全に保存するのか？」**

**彼らの答え: 「するな(もしどうしてもなら、難読化に害なし)」**

**Comment by sorakoro** [comment]
前回の続き
ユーザー画面の設計について

**Comment by hiranodept** [comment]
## [The 15 Best WWDC Videos of All Time](https://www.hackingwithswift.com/articles/190/the-best-wwdc-videos-of-all-time)

Best3は以下
### 1. Protocol-Oriented Programming in Swift
Year: 2015   Difficulty: Intermediate

### 2. Advanced NSOperations
Year: 2015   Difficulty: Advanced

### 3. Testing Tips & Tricks
Year: 2018   Difficulty: Intermediate

先日、樫原さんとランチタイムビデオで iOSDCの`Heart of Swift`を観た
ここでも`Protocol-Oriented Programming` と`Value Semantics`の話をしていて
とてもためになった。SwiftUIの書き方の部分でもとても参考になる。
[Heart of Swift]( https://fortee.jp/iosdc-japan-2019/proposal/8c0509d1-ec1d-4225-8e04-e92726f997d4)

**Comment by takashings** [comment]
## Apple Event. December 2 in NYC.
Apple Special event honoring our favorite apps and games of 2019.
https://twitter.com/LanceUlanoff/status/1196541112992829440

**Comment by hiranodept** [comment]
## Peopleの申請・リリースフロー

![スクリーンショット 2019-11-19 18 08 48](https://user-images.githubusercontent.com/1940104/69134553-febb2200-0afa-11ea-9fa2-af0e3ac222ce.png)

人間がやることは以下の3つ
- Slackで `/bitrise-yashima-ios branch: develop | workflow: prepare_release` を実行
- AppStoreConnectにてリリースボタンを押す
- GithubにてReleaseブランチをmasterにマージする

**Comment by ngtk** [comment]
今日できなかったトピックは来週のIssueに移してもらえると嬉しいです。 👉 https://github.com/wantedly/ios_night/issues/76
